global-options:
    nsamps: 2000
    scenario: ssp585
    pyear_start: 2020
    pyear_end: 2150
    pyear_step: 10
    baseyear: 2005

climate_step:
    temperature:
        module_set: "fair"
        module: "temperature"
        generates_climate_output: true
#        input_data_file:
#              - "emissions.csv"
#        options:
#              rcmip_file: emissions.csv
